apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wansjey7i-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wansjey7i-python 
  name: wansjey7i-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wansjey7i-python 
